route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: email-notifications

receivers:
  - name: email-notifications
    email_configs:
      - to: tusharburkul10@gmail.com
        from: monitoring@example.com
        smarthost: smtp.gmail.com:587
        auth_username: tusharburkul10@gmail.com
        auth_identity: tusharburkul10@gmail.com
        auth_password: 'egiu xcqr xvju'  # Ensure you replace this with a valid app password
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'dev', 'instance']
